type MonthlyReportEntry = {
  title?: string;
  status?: string;
  time?: string;
  price?: number;
};

type MonthlyReportPayload = {
  month: string;
  dealerName?: string;
  email?: string;
  phone?: string;
  generatedAt: Date;
  totalListings: number;
  activeListings: number;
  pendingListings: number;
  totalValue: number;
  soldValue: number;
  avgPrice: number;
  successRate: number;
  entries: MonthlyReportEntry[];
};

const pageWidth = 595;
const pageHeight = 842;
const margin = 42;
const lineHeight = 16;

const escapePdfText = (value: unknown) =>
  String(value ?? "")
    .replace(/\\/g, "\\\\")
    .replace(/\(/g, "\\(")
    .replace(/\)/g, "\\)")
    .replace(/\r?\n/g, " ");

const money = (value: number) =>
  new Intl.NumberFormat("en-CA", {
    style: "currency",
    currency: "CAD",
    maximumFractionDigits: 0,
  }).format(Number(value || 0));

const text = (
  value: unknown,
  x: number,
  y: number,
  size = 10,
  font = "F1",
  color = "0 0 0"
) => `BT /${font} ${size} Tf ${color} rg ${x} ${y} Td (${escapePdfText(value)}) Tj ET\n`;

const rect = (
  x: number,
  y: number,
  width: number,
  height: number,
  color = "1 1 1"
) => `${color} rg ${x} ${y} ${width} ${height} re f\n`;

const line = (
  x1: number,
  y1: number,
  x2: number,
  y2: number,
  color = "0.86 0.88 0.91",
  width = 0.8
) => `${color} RG ${width} w ${x1} ${y1} m ${x2} ${y2} l S\n`;

const truncate = (value: unknown, max: number) => {
  const textValue = String(value ?? "");
  return textValue.length > max ? `${textValue.slice(0, max - 3)}...` : textValue;
};

const buildHeader = (payload: MonthlyReportPayload) => {
  let stream = "";

  stream += rect(0, pageHeight - 92, pageWidth, 92, "0.97 0.98 1");
  stream += line(margin, pageHeight - 92, pageWidth - margin, pageHeight - 92, "0.75 0.82 0.93", 1);
  stream += text("1", margin, pageHeight - 54, 30, "F2", "0 0.208 0.478");
  stream += text("ntel", margin + 17, pageHeight - 54, 30, "F2", "0.02 0.03 0.06");
  stream += text("Monthly Analytics Report", pageWidth - 240, pageHeight - 44, 17, "F2", "0.02 0.03 0.06");
  stream += text(payload.month, pageWidth - 240, pageHeight - 66, 11, "F1", "0.32 0.37 0.45");

  return stream;
};

const buildSummaryCards = (payload: MonthlyReportPayload, startY: number) => {
  const cards = [
    ["Total Listings", String(payload.totalListings)],
    ["Active", String(payload.activeListings)],
    ["Pending", String(payload.pendingListings)],
    ["Total Value", money(payload.totalValue)],
    ["Sold Value", money(payload.soldValue)],
    ["Avg Price", money(payload.avgPrice)],
    ["Success Rate", `${payload.successRate}%`],
  ];

  let stream = "";
  let x = margin;
  let y = startY;
  const cardW = 158;
  const cardH = 54;

  cards.forEach(([label, value], index) => {
    if (index > 0 && index % 3 === 0) {
      x = margin;
      y -= cardH + 12;
    }

    stream += rect(x, y, cardW, cardH, "1 1 1");
    stream += line(x, y, x + cardW, y, "0.87 0.9 0.94", 0.7);
    stream += line(x, y + cardH, x + cardW, y + cardH, "0.87 0.9 0.94", 0.7);
    stream += line(x, y, x, y + cardH, "0.87 0.9 0.94", 0.7);
    stream += line(x + cardW, y, x + cardW, y + cardH, "0.87 0.9 0.94", 0.7);
    stream += text(label, x + 12, y + 34, 9, "F1", "0.38 0.43 0.5");
    stream += text(value, x + 12, y + 14, 14, "F2", "0.02 0.03 0.06");
    x += cardW + 14;
  });

  return { stream, nextY: y - 34 };
};

const buildFooter = (pageNumber: number) => {
  let stream = "";
  stream += line(margin, 34, pageWidth - margin, 34, "0.86 0.88 0.91", 0.7);
  stream += text("Generated by 1ntel", margin, 18, 8, "F1", "0.42 0.47 0.55");
  stream += text(`Page ${pageNumber}`, pageWidth - margin - 42, 18, 8, "F1", "0.42 0.47 0.55");
  return stream;
};

const createPdf = (pageStreams: string[]) => {
  const objects: string[] = [];
  const pageObjectIds: number[] = [];

  objects.push("<< /Type /Catalog /Pages 2 0 R >>");
  objects.push("");
  objects.push("<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>");
  objects.push("<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica-Bold >>");

  pageStreams.forEach((stream) => {
    const contentObjectId = objects.length + 1;
    objects.push(`<< /Length ${stream.length} >>\nstream\n${stream}endstream`);

    const pageObjectId = objects.length + 1;
    pageObjectIds.push(pageObjectId);
    objects.push(
      `<< /Type /Page /Parent 2 0 R /MediaBox [0 0 ${pageWidth} ${pageHeight}] /Resources << /Font << /F1 3 0 R /F2 4 0 R >> >> /Contents ${contentObjectId} 0 R >>`
    );
  });

  objects[1] = `<< /Type /Pages /Kids [${pageObjectIds.map((id) => `${id} 0 R`).join(" ")}] /Count ${pageObjectIds.length} >>`;

  let pdf = "%PDF-1.4\n";
  const offsets = [0];

  objects.forEach((object, index) => {
    offsets.push(pdf.length);
    pdf += `${index + 1} 0 obj\n${object}\nendobj\n`;
  });

  const xrefOffset = pdf.length;
  pdf += `xref\n0 ${objects.length + 1}\n0000000000 65535 f \n`;
  offsets.slice(1).forEach((offset) => {
    pdf += `${String(offset).padStart(10, "0")} 00000 n \n`;
  });
  pdf += `trailer\n<< /Size ${objects.length + 1} /Root 1 0 R >>\nstartxref\n${xrefOffset}\n%%EOF`;

  return pdf;
};

export const downloadMonthlyAnalyticsPdf = (payload: MonthlyReportPayload) => {
  const pages: string[] = [];
  let stream = buildHeader(payload);

  stream += text("Dealer Details", margin, 716, 13, "F2", "0.02 0.03 0.06");
  stream += text(`Name: ${payload.dealerName || "Dealer"}`, margin, 694, 10, "F1", "0.25 0.29 0.35");
  stream += text(`Email: ${payload.email || "-"}`, margin, 678, 10, "F1", "0.25 0.29 0.35");
  stream += text(`Phone: ${payload.phone || "-"}`, margin, 662, 10, "F1", "0.25 0.29 0.35");
  stream += text(
    `Generated: ${payload.generatedAt.toLocaleString()}`,
    pageWidth - 240,
    694,
    10,
    "F1",
    "0.25 0.29 0.35"
  );

  const summary = buildSummaryCards(payload, 580);
  stream += summary.stream;

  let y = summary.nextY;
  stream += text("Listing Details", margin, y, 13, "F2", "0.02 0.03 0.06");
  y -= 22;
  stream += rect(margin, y - 6, pageWidth - margin * 2, 24, "0.94 0.97 1");
  stream += text("Date", margin + 8, y + 2, 9, "F2", "0.02 0.03 0.06");
  stream += text("Listing", margin + 118, y + 2, 9, "F2", "0.02 0.03 0.06");
  stream += text("Status", pageWidth - 175, y + 2, 9, "F2", "0.02 0.03 0.06");
  stream += text("Price", pageWidth - 95, y + 2, 9, "F2", "0.02 0.03 0.06");
  y -= 18;

  const rows = payload.entries.length
    ? payload.entries
    : [{ time: "-", title: "No listings in this month", status: "-", price: 0 }];

  rows.forEach((entry, index) => {
    if (y < 64) {
      stream += buildFooter(pages.length + 1);
      pages.push(stream);
      stream = buildHeader(payload);
      y = 710;
      stream += text("Listing Details Continued", margin, y, 13, "F2", "0.02 0.03 0.06");
      y -= 26;
    }

    if (index % 2 === 0) {
      stream += rect(margin, y - 5, pageWidth - margin * 2, 20, "0.985 0.987 0.99");
    }

    stream += text(truncate(entry.time, 18), margin + 8, y, 8.5, "F1", "0.25 0.29 0.35");
    stream += text(truncate(entry.title || "Untitled listing", 40), margin + 118, y, 8.5, "F1", "0.12 0.15 0.2");
    stream += text(truncate(entry.status || "-", 14), pageWidth - 175, y, 8.5, "F1", "0.25 0.29 0.35");
    stream += text(money(entry.price || 0), pageWidth - 95, y, 8.5, "F2", "0.02 0.03 0.06");
    y -= lineHeight;
  });

  stream += buildFooter(pages.length + 1);
  pages.push(stream);

  const pdf = createPdf(pages);
  const blob = new Blob([pdf], { type: "application/pdf" });
  const url = URL.createObjectURL(blob);
  const link = document.createElement("a");
  link.href = url;
  link.download = `1ntel-${payload.month.replace(/\s+/g, "-").toLowerCase()}-analytics.pdf`;
  document.body.appendChild(link);
  link.click();
  link.remove();
  URL.revokeObjectURL(url);
};
